(GH-310) Adds Uninstall-ChocolateyPath and now respects semicolons in paths
chocolatey/choco pull request #1663
Opened 2018-10-17 19:42 UTC by jnm2

Closes #310.

Discussion:
- https://github.com/chocolatey/choco/pull/1019#discussion_r164261454
- https://github.com/chocolatey/choco/pull/1019#issuecomment-360983979

2018-10-17 20:28 UTC, franklinyu commented
I think this should also close #1019?

2018-10-17 20:34 UTC, jnm2 commented
1019 is a PR. Does it make sense to autoclose one PR from another?

2018-10-18 02:38 UTC, franklinyu commented
Makes sense to me, because this PR supersedes #1019.

2019-02-06 22:55 UTC, jnm2 commented
@gep13 Is there anything I can do to help get this merged?

2020-06-08 14:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/chocolatey/choco?pullRequest=1663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/chocolatey/choco?pullRequest=1663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/chocolatey/choco?pullRequest=1663) it.</sub>

2021-07-22 15:50 UTC, jtcmedia commented
Is this going to get merged? It would be extremely useful.

2021-07-26 02:21 UTC, jmcker requested changes

2021-07-26 02:21 UTC, jmcker commented on src/chocolatey.resources/helpers/functions/Uninstall-ChocolateyPath.ps1
> +    Write-Host "PATH environment variable does not have $pathToUninstall in it. Adding..."
This condition (and even the log) are identical to `Chocolatey-InstallPath`. I'm assuming it's supposed to be something more like:

`$removeIndex` is also not defined.

```suggestion
  $removeIndex = (IndexOf-EnvPath $paths $pathToUninstall)
  if ($removeIndex -ge 0) {
    Write-Host "Found $pathToUninstall in PATH environment variable. Removing..."
```

2021-07-26 02:21 UTC, jmcker commented on src/chocolatey.resources/helpers/functions/Uninstall-ChocolateyPath.ps1
> +  if ((IndexOf-EnvPath $paths $pathToUninstall) -eq -1) {
Same deal as above.

```suggestion
  $removeIndex = (IndexOf-EnvPath $paths $pathToUninstall)
  if ($removeIndex -ge 0) {
```

2022-11-27 05:22 UTC, jmooring commented
@gep13 Can you or someone else on your team have a look at this, please.

2022-11-27 11:05 UTC, pauby commented
Please don't ping people on PR's. We are aware of all of the PR's and will look at them when we are able to.

2023-04-18 14:31 UTC, dazeeeed commented
Amazing that this PR is still not merged in 2023, this is such a great feature.

2024-04-19 15:03 UTC, vexx32 commented
Apologies for the long wait on this PR. This work is being incorporated into a larger scope of work involving some rewrites that will be submitted soon, so for now we'll close this PR.

Thank you very much for the contribution, this was a really good place to start! 💜

2024-04-19 15:03 UTC, closed without merging