(GH-2044) Fix for changing $env:Temp
chocolatey/choco pull request #2154
Opened 2020-11-27 16:27 UTC by teknowledgist

(GH-2044) This fixes a problem when a package is installed under the System credentials (typically how centralized management software -- e.g. SCCM -- operate):

Running as `SYSTEM`, the `$env:Temp` variable is normally *C:\Windows\Temp*. If the **first** package to ever use `Update-SessionEnvironment.ps1` happens to be running as `SYSTEM`, the location of `$env:Temp` changes to *C:\Windows\system32\config\systemprofile\AppData\Local\Temp* for the duration of the session.  This change to `$env:Temp` does not occur in subsequent calls to `Update-SessionEnvironment.ps1`.  It is unknown why this change occurs at all and likewise is unknown why it occurs for only the first time.

The `Update-SessionEnvironment.ps1` normally gives priority to user-scope environment variables over machine-scope environment variables.  Changes in this commit eliminates the gathering of the `User` scope environment variables when running as the `SYSTEM` account on the belief that reason to be operating under the `SYSTEM` account is to do machine-wide activities, and there is no reason to see `SYSTEM` as a "user".  On a clean system, the only User-scope environment variables under `SYSTEM` are *path*, *temp*, and *tmp* which are already defined under the Machine-scope, and in general, there shouldn't be any new User-scope variables for the SYSTEM account because it's not a "normal" account.  Basically, there should be little reason to expect this change to break anything.

2021-04-19 06:55 UTC, gep13 commented
@vexx32 any chance you can take a look at this one, thanks?

2021-04-19 12:59 UTC, vexx32 requested changes
Overall looks good to me. A few things here and there I think we should clean up a bit before we merge. 🙂

2021-04-19 12:59 UTC, vexx32 commented on src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1
> +  if (($userName -ne 'SYSTEM') -and ($userName -ne "$($env:COMPUTERNAME)`$")) {
This might be clearer to write as:
```suggestion
  if ($userName -notin 'SYSTEM', "${env:COMPUTERNAME}`$") {

```

2021-04-19 12:59 UTC, vexx32 commented on src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1
> +  foreach ($Scope in $Scopes) {
I generally recommend avoiding plural variables be used alongside singular counterparts; it's very easy to mess things up with a single-character typo and not notice that the logic is totally broken until later. Maybe use `$ScopeList` instead for the latter variable?

2021-04-19 12:59 UTC, vexx32 commented on src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1
> +          Set-Item "Env:$($_)" -Value (Get-EnvironmentVariable -Scope $Scope -Name $_)
Unnecessary subexpression wrapper in this string
```suggestion
          Set-Item "Env:$_" -Value (Get-EnvironmentVariable -Scope $Scope -Name $_)
```

2021-04-19 14:52 UTC, teknowledgist commented
I agree with all the comments by @vexx32 and I *think* I've made the adjustments so they roll into this PR.  (I'm not very good with GitHub and how the change management flow works.)

2021-04-19 15:10 UTC, vexx32 approved these changes
Looks good to me, thanks for fixing that up! 💖

2021-05-05 12:13 UTC, gep13 approved these changes
LGTM!

2021-05-05 12:21 UTC, merged

2021-05-05 12:21 UTC, gep13 commented
@teknowledgist thank you very much for taking the time to submit this PR, we really appreciate it!