(#2762, #2710) Update testing to include testing of stable Chocolatey builds
chocolatey/choco pull request #2766
Opened 2022-07-14 21:31 UTC by corbob

## Description Of Changes

* Update the Vagrantfile used for running tests to be able to run tests against stable releases.
* Update Contributing.md to move testing section into Testing.md.

## Motivation and Context

We need to ensure that newly added tests also succeed with currently stable versions of Chocolatey. If they do not, then they need to be gated on the Chocolatey version so that failing tests aren't accidentally introduced.

## Testing

1. Ran `vagrant up TestStable` while this branch was based upon commit cce748
1. Verified that tests failed
2. Ran `vagrant up`
3. Verified that tests passed
4. Rebased branch off of current develop (136f1c)
5. Ran `vagrant destroy -f`
6. Ran `vagrant up TestStable`
7. Verified that tests passed
8. ran `vagrant up`
9. verified that tests passed

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #2762 
Fixes #2710

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2023-07-12 06:46 UTC, gep13 commented
@corbob just wanted to check that you intended to close this PR, since the two linked issues are still open.

2023-07-12 14:49 UTC, corbob commented
I was doing cleanup of my repositories last night, and either missed that this branch had a PR, or GitKraken didn't show it. In either case it was unintentional to close. I have closed one of the linked issues, as it's not actually needed due to process changes. I'll restore this branch to hopefully get back to updating the testing instructions.

2024-02-14 14:00 UTC, gep13 requested changes
Some small bits of feedback

2024-02-15 21:01 UTC, corbob commented on TESTING.md
> +However, this execution pattern is not necessarily guaranteed and
Yeah, it looks like I got distracted while writing this and didn't finish it. I've revamped this section.

2024-02-15 21:02 UTC, corbob commented on TESTING.md
> +Whenever possible, it should be possible to identify exactly when a line of code will be executed during a test run.
As with the other comment about it ending abruptly: Yeah, it looks like I got distracted while writing this and didn't finish it. I've revamped this section.

2024-02-15 21:04 UTC, corbob commented on TESTING.md
> +Coinciding with that tests should be self container, they should also not depend on other tests running in a specific order.
Reading over this section again, I didn't like the use of the `coinciding` part. It felt like using big words just for the sake of using big words.

2024-02-15 21:04 UTC, corbob commented on TESTING.md
> +Below is a list of words.
This line is practically perfect in every way! (or yeah, doesn't make a lick of sense 😂 )

2024-02-18 08:43 UTC, gep13 approved these changes
LGTM!

2024-02-18 08:43 UTC, merged

2024-02-18 08:43 UTC, gep13 commented
@corbob thanks for getting this updated!