(#2893) Switch from Should to FluentAssertions
chocolatey/choco pull request #2908
Opened 2022-11-18 00:48 UTC by TheCakeIsNaOH

## Description Of Changes

This switches chocolatey.tests and chocolatey.tests.integration to use FluentAssertions instead of Should. This is because Should is no longer actively maintained, so it is time to replace it.

As per the FluentAssertions api, various calls needed to be adjusted, mostly in the pattern Shouldxxxx() to Should().xxxx()

## Motivation and Context

See #2893

## Testing

TODO

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [x] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #2893

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2022-11-18 00:52 UTC, TheCakeIsNaOH commented
It looks like FluentAssertions 6.x is not compatible with Visual Studio 2017. 
https://stackoverflow.com/questions/68911113/ambiguous-call-when-using-should-notbenull-on-as-item

Since I have Visual Studio 2017 installed locally, the `build.ps1` fails, as it tries to use MSBuild from vs 2017. However, I can build with Visual Studio 2022. That is why this is currently in draft.

2022-11-18 07:26 UTC, gep13 commented
> @TheCakeIsNaOH said...
It looks like FluentAssertions 6.x is not compatible with Visual Studio 2017.
https://stackoverflow.com/questions/68911113/ambiguous-call-when-using-should-notbenull-on-as-item

What happens if you change the `langVersion` in the csproj file to `7.3`?

2022-11-18 20:26 UTC, TheCakeIsNaOH commented
@gep13 that fixed it.
I've pushed a commit with the change.

2022-12-14 09:43 UTC, AdmiringWorm requested changes
I have done a partial review to have something to get started on, and similar changes would be needed for the rest of the files.

2023-06-04 03:29 UTC, TheCakeIsNaOH commented on src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
> +                messageFound.Should().BeTrue("GUI false message not found");
This is not a method that uses the MockLogger, so should be fine as is.

2023-06-04 03:29 UTC, TheCakeIsNaOH commented on src/chocolatey.tests.integration/scenarios/InstallScenarios.cs
> +                messageFound.Should().BeTrue("GUI true message not found");
This is not a method that uses the MockLogger, so should be fine as is.

2023-06-04 03:58 UTC, TheCakeIsNaOH commented
This is ready for a re-review, I think I completed the suggested changes across the various test files.

2023-06-05 14:22 UTC, AdmiringWorm requested changes
Some items I think should be fixed so that we have a reference when adding new tests.

Do note that there are quite a few other places that will benefit for similar changes that I haven't commented on, however only the ones I have commented on are required to be fixed at this moment.

2023-06-05 14:22 UTC, AdmiringWorm commented on src/chocolatey/app.config
Please remove this file

2023-06-06 09:59 UTC, AdmiringWorm approved these changes
LGTM, but had to downgrade the `System.Runtime.CompilerServices.Unsafe` dependency as it causes problems with the build system, and we want to keep it closer to the version in other projects.

2023-06-06 12:06 UTC, AdmiringWorm approved these changes
LGTM

2023-06-06 12:07 UTC, merged

2023-06-06 12:07 UTC, AdmiringWorm commented
@TheCakeIsNaOH your changes have been merged. Thanks for your contribution 👍