(maint) Fix grammatical issue in pending reboot warning message
chocolatey/choco pull request #3164
Opened 2023-05-20 10:06 UTC by sorousherafat

## Description Of Changes
Changed 'Pending Reboot' warning message to be more accurate grammatically.

## Motivation and Context

## Testing

### Operating Systems Testing

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [x] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

Fixes no issue

2023-05-20 10:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/chocolatey/choco?pullRequest=3164) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/chocolatey/choco?pullRequest=3164) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/chocolatey/choco?pullRequest=3164) it.</sub>

2024-04-19 11:36 UTC, pauby requested changes
I feel this reads better.

2024-04-19 11:36 UTC, pauby commented on src/chocolatey/infrastructure.app/validations/SystemStateValidation.cs
> +   being ignored due to the current command used being '{0}'.
```suggestion
   being ignored due to the current command '{0}' being used.

```

2024-04-19 11:53 UTC, gep13 commented on src/chocolatey/infrastructure.app/validations/SystemStateValidation.cs
> +   being ignored due to the current command used being '{0}'.
Yes, I agree, I will get this fixed up.

2024-04-19 11:54 UTC, gep13 commented
@sorousherafat thank you very much for taking the time to raise this PR to highlight this problem.  After discussing with @pauby we are going to move forward with his suggestion, and I have taken the liberty to update this PR with his suggestions.

2024-04-19 11:58 UTC, gep13 commented
Not sure why the CLA check is being marked as not there:

<img width="1181" alt="image" src="https://github.com/chocolatey/choco/assets/1271146/73bac623-9c0c-4d8f-948c-e5a3a2d0282d">

but it has been signed, as per this comment:

https://github.com/chocolatey/choco/pull/3164#issuecomment-1555878866

2024-04-19 11:58 UTC, gep13 approved these changes
LGTM!

2024-04-19 12:02 UTC, merged