(#3501) Remove old install migration code
chocolatey/choco pull request #3528
Opened 2024-10-07 18:41 UTC by vexx32

## Description Of Changes
- Remove code relating to migration from a `C:\chocolatey` install folder from the `chocolateysetup.psm1` module used for installing Chocolatey.

## Motivation and Context
This migration path hasnt been supported or used since pre-1.0 versions of Chocolatey and is dead code.

Removing this now to simplify the install process somewhat and get the old code out of the way as it's not used at all.

## Testing

1. Run `build.ps1` to generate a package
2. Copy the generated nupkg to a fresh VM and take a snapshot
3. Install Chocolatey using the following PowerShell code from an admin shell, substituting the nupkg path for the nupkg you copied over:
   ```powershell
   ${function:Install-Choco} = [scriptblock]::Create((Invoke-WebRequest https://community.chocolatey.org/install.ps1))
   Install-Choco -ChocolateyDownloadUrl ./path/to/chocolatey.nupkg
   ```
4. Ensure the installation completes successfully
5. Downgrade choco to 2.3.0:  `choco upgrade chocolatey --allow-downgrade --version 2.3.0 --allow-unofficial`
6. Upgrade choco once again to the built nupkg to ensure the upgrade works appropriately: `choco upgrade chocolatey --source ./path/to/nupkg/folder --pre`
7. Ensure the upgrade completes successfully
8. Restore from snapshot
9. Set `$env:ChocolateyInstall = 'C:\Users\YOUR_USERNAME\chocolatey'`
10. Repeat from step 3 _in a non-admin shell_ to verify things work with a non-admin install as well

### Operating Systems Testing

Windows 10

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [x] All new and existing tests passed?
* [x] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue

Fixes #3501

2024-10-07 19:14 UTC, corbob reviewed
Code wise this looks good. I still need to give it a test locally.

2024-10-08 11:54 UTC, gep13 requested changes

2024-10-08 11:54 UTC, gep13 commented on nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
>  $sysDrive = $env:SystemDrive
This can be removed as well, right?

2024-10-08 19:03 UTC, vexx32 commented on nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
>  $sysDrive = $env:SystemDrive
Yep, looks like, good catch! Removed :3

2024-10-16 15:59 UTC, vexx32 commented on nuspec/chocolatey/chocolatey/tools/chocolateysetup.psm1
> +    if ($alreadyInitializedNugetPath -and $alreadyInitializedNugetPath -ne $chocolateyPath -and $allowInsecureRootInstall) {
I think I have this sorted for now :3

2024-10-29 20:37 UTC, corbob approved these changes
Looks good to me.

2024-10-29 21:22 UTC, merged