WIP: Auth fixes for 1.x
chocolatey/choco pull request #3572
Opened 2024-11-22 01:37 UTC by corbob

This is WIP while I get tests running in Team City.

## Description Of Changes

## Motivation and Context

## Testing

### Operating Systems Testing

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue

Fixes #

2024-11-25 20:32 UTC, vexx32 approved these changes
LGTM! One small comment. About a comment.

2024-11-25 20:32 UTC, vexx32 commented on src/chocolatey/infrastructure.app/nuget/ChocolateyNugetCredentialProvider.cs
> +                // while ignoring #fragments on the URLs, but does care about trailing slashes, which we do not here.
Same as on the other PR, we're not using this, so we should remove this comment.

2024-11-25 20:43 UTC, vexx32 approved these changes

2024-11-26 09:39 UTC, gep13 commented on tests/pester-tests/features/CredentialProvider.Tests.ps1
> +﻿Describe 'Ensuring credentials do not bleed from configured sources' -Tag CredentialProvider -ForEach @(
Same comment here, as per the other PR. I think we need more words here as to what this test is doing, and why the asserts are set the way that they are.

2024-11-26 09:40 UTC, gep13 requested changes
Couple things here that I think needs to be addressed.

2024-11-26 17:05 UTC, gep13 approved these changes
LGTM!

2024-11-26 19:07 UTC, merged